version: "#{build}"
clone_depth: 1

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "stable"

install:
- ps: Install-Product node $env:nodejs_version
- cmd: >-
    node --version

    npm --version

    npm install

build: off
test_script:
- cmd: npm test
